# Generated by Django 6.0.2 on 2026-03-01 01:41

import django.db.models.deletion
import proyectoBanders.clientes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='Cédula/ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=proyectoBanders.clientes.models.path_cliente_foto)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Domiciliaria')),
                ('estado_operativo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente')], default='activo', max_length=20, verbose_name='Estado Operativo')),
                ('esta_activo', models.BooleanField(default=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('otro', 'Otro')], default='soltero', max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, choices=[('azuay', 'Azuay'), ('bolivar', 'Bolívar'), ('cañar', 'Cañar'), ('carchi', 'Carchi'), ('chimborazo', 'Chimborazo'), ('cotopaxi', 'Cotopaxi'), ('el_oro', 'El Oro'), ('esmeraldas', 'Esmeraldas'), ('galapagos', 'Galápagos'), ('guayas', 'Guayas'), ('imbabura', 'Imbabura'), ('loja', 'Loja'), ('los_rios', 'Los Ríos'), ('manabi', 'Manabí'), ('morona_santiago', 'Morona Santiago'), ('napo', 'Napo'), ('orellana', 'Orellana'), ('pastaza', 'Pastaza'), ('pichincha', 'Pichincha'), ('santa_elena', 'Santa Elena'), ('santo_domingo', 'Santo Domingo'), ('sucumbios', 'Sucumbíos'), ('tungurahua', 'Tungurahua'), ('zamora_chinchipe', 'Zamora Chinchipe')], max_length=50, null=True)),
                ('canton', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nombre del Documento')),
                ('categoria', models.CharField(choices=[('identidad', 'Cédula / Pasaporte'), ('contrato', 'Contratos / Convenios'), ('poder', 'Poderes Judiciales'), ('evidencia', 'Evidencias / Pruebas'), ('pago', 'Comprobantes de Pago'), ('otros', 'Otros Documentos')], default='otros', max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción opcional')),
                ('archivo', models.FileField(upload_to=proyectoBanders.clientes.models.path_documentos_cliente)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
