# Generated by Django 6.0.2 on 2026-02-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Domiciliaria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_operativo',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente')], default='activo', max_length=20, verbose_name='Estado Operativo'),
        ),
    ]
