# Generated by Django 6.0.2 on 2026-02-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_direccion_cliente_estado_operativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentocliente',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de Cliente', 'verbose_name_plural': 'Documentos de Clientes'},
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='categoria',
            field=models.CharField(choices=[('identidad', 'Cédula / Pasaporte'), ('contrato', 'Contratos / Convenios'), ('poder', 'Poderes Judiciales'), ('evidencia', 'Evidencias / Pruebas'), ('pago', 'Comprobantes de Pago'), ('otros', 'Otros Documentos')], default='otros', max_length=30),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción opcional'),
        ),
    ]
