# Generated by Django 6.0.2 on 2026-02-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deuda', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='expedientes.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_abono', models.DateTimeField(auto_now_add=True)),
                ('pago_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='pagos.pago')),
            ],
        ),
    ]
