# Generated by Django 6.0.2 on 2026-03-01 01:41

import django.db.models.deletion
import proyectoBanders.pagos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('honorarios', 'Honorarios Profesionales'), ('gastos_judiciales', 'Gastos Judiciales / Tasas'), ('peritaje', 'Servicios de Peritaje'), ('otros', 'Otros Conceptos')], default='honorarios', max_length=50)),
                ('total_deuda', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transaccion_id', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas_pago', models.TextField(blank=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='expedientes.expediente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_abono', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('tarjeta', 'Tarjeta de Crédito/Débito')], default='transferencia', max_length=50)),
                ('comprobante_file', models.FileField(blank=True, null=True, upload_to=proyectoBanders.pagos.models.path_comprobante_pago)),
                ('referencia_bancaria', models.CharField(blank=True, max_length=100, null=True)),
                ('pago_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='pagos.pago')),
            ],
        ),
    ]
