# Generated by Django 6.0.2 on 2026-02-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
