# Generated by Django 6.0.2 on 2026-02-17 03:28

import pagos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_options_pago_transaccion_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Registro de Pago', 'verbose_name_plural': 'Registros de Pagos'},
        ),
        migrations.AddField(
            model_name='abono',
            name='comprobante_file',
            field=models.FileField(blank=True, null=True, upload_to=pagos.models.path_comprobante_pago),
        ),
        migrations.AddField(
            model_name='abono',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('tarjeta', 'Tarjeta de Crédito/Débito')], default='transferencia', max_length=50),
        ),
        migrations.AddField(
            model_name='abono',
            name='referencia_bancaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('honorarios', 'Honorarios Profesionales'), ('gastos_judiciales', 'Gastos Judiciales / Tasas'), ('peritaje', 'Servicios de Peritaje'), ('otros', 'Otros Conceptos')], default='honorarios', max_length=50),
        ),
        migrations.AddField(
            model_name='pago',
            name='notas_pago',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Abonado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='total_deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(default='TEMP-000', max_length=100, unique=True, verbose_name='Referencia Global'),
            preserve_default=False,
        ),
    ]
