# Generated by Django 6.0.2 on 2026-02-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariocustom',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario del Consorcio', 'verbose_name_plural': 'Usuarios del Consorcio'},
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='rol',
            field=models.CharField(choices=[('abogado', 'Abogado'), ('contador', 'Contador'), ('psicologo', 'Psicólogo'), ('administrador', 'Administrador'), ('marketing', 'Marketing')], default='abogado', max_length=20, verbose_name='Rol en el Consorcio'),
        ),
    ]
