# Generated by Django 6.0.2 on 2026-03-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariocustom_options_alter_usuariocustom_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='esta_aprobado',
            field=models.BooleanField(default=False, help_text='Marque esta casilla para permitir que el usuario acceda al sistema.', verbose_name='Aprobado por Administración'),
        ),
    ]
