# Generated by Django 6.0.2 on 2026-03-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuariocustom_esta_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='esta_aprobado',
            field=models.BooleanField(default=False, help_text='Indica si el administrador ha permitido el acceso a este usuario.', verbose_name='Cuenta Aprobada'),
        ),
    ]
