# Generated by Django 6.0.2 on 2026-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuariocustom_esta_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='esta_aprobado',
            field=models.BooleanField(default=False, verbose_name='¿Usuario Aprobado?'),
        ),
    ]
