# Generated by Django 6.0.2 on 2026-04-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuariocustom_esta_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='username',
            field=models.CharField(blank=True, help_text='Requerido. 150 caracteres o menos.', max_length=150, null=True, unique=True, verbose_name='nombre de usuario'),
        ),
    ]
