# Generated by Django 6.0.2 on 2026-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuariocustom_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='nombre de usuario'),
        ),
    ]
