# Generated by Django 6.0.2 on 2026-03-01 01:41

import django.db.models.deletion
import proyectoBanders.expedientes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Caso')),
                ('numero_proceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Proceso / Causa')),
                ('tipo_expediente', models.CharField(choices=[('penal', '⚖️ Penal'), ('civil', '📜 Civil'), ('laboral', '👷 Laboral'), ('familia', '🏠 Familia'), ('administrativo', '📂 Administrativo'), ('migratorio', '✈️ Migratorio')], default='civil', max_length=50)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='abierto', max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', '🟢 Baja'), ('media', '🟡 Media'), ('alta', '🔴 Alta')], default='media', max_length=10)),
                ('honorarios_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_juridicos', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to=proyectoBanders.expedientes.models.path_documentos_expediente)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_expediente', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='NotaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Actuación / Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_seguimiento', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Nota de Seguimiento',
                'verbose_name_plural': 'Notas de Seguimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
