# Generated by Django 6.0.2 on 2026-02-16 22:45

import django.db.models.deletion
import expedientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to=expedientes.models.path_documentos_expediente, verbose_name='Documento Digital')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento de Expediente',
                'verbose_name_plural': 'Documentos de Expedientes',
            },
        ),
        migrations.CreateModel(
            name='NotaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Observación/Nota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota de Seguimiento',
                'verbose_name_plural': 'Notas de Seguimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Expediente')),
                ('numero_proceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Proceso/Causa')),
                ('tipo_expediente', models.CharField(default='civil', max_length=50, verbose_name='Materia/Tipo')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('suspendido', 'Suspendido'), ('finalizado', 'Finalizado'), ('archivo_muerto', 'Archivo Muerto')], default='abierto', max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Resumen del Caso')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_juridicos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
