# Generated by Django 6.0.2 on 2026-02-17 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoexpediente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_expediente', to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_expediente',
            field=models.CharField(choices=[('penal', 'Penal'), ('civil', 'Civil'), ('laboral', 'Laboral'), ('familia', 'Familia'), ('administrativo', 'Administrativo'), ('constitucional', 'Constitucional')], default='civil', max_length=50, verbose_name='Materia/Tipo'),
        ),
        migrations.AlterField(
            model_name='notaexpediente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_seguimiento', to='expedientes.expediente'),
        ),
    ]
