# Generated by Django 6.0.2 on 2026-02-17 02:39

import django.db.models.deletion
import expedientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('expedientes', '0003_alter_documentoexpediente_expediente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoexpediente',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='expediente',
            name='honorarios_totales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='documentoexpediente',
            name='archivo',
            field=models.FileField(upload_to=expedientes.models.path_documentos_expediente),
        ),
        migrations.AlterField(
            model_name='documentoexpediente',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del Documento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_juridicos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='abierto', max_length=50),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_proceso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Proceso / Causa'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='prioridad',
            field=models.CharField(choices=[('baja', '🟢 Baja'), ('media', '🟡 Media'), ('alta', '🔴 Alta')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_expediente',
            field=models.CharField(choices=[('penal', '⚖️ Penal'), ('civil', '📜 Civil'), ('laboral', '👷 Laboral'), ('familia', '🏠 Familia'), ('administrativo', '📂 Administrativo')], default='civil', max_length=50),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título del Caso'),
        ),
        migrations.AlterField(
            model_name='notaexpediente',
            name='contenido',
            field=models.TextField(verbose_name='Actuación / Comentario'),
        ),
    ]
