# Generated by Django 6.0.2 on 2026-02-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_alter_documentoexpediente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoexpediente',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Documento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_expediente',
            field=models.CharField(choices=[('penal', '⚖️ Penal'), ('civil', '📜 Civil'), ('laboral', '👷 Laboral'), ('familia', '🏠 Familia'), ('administrativo', '📂 Administrativo'), ('migratorio', '✈️ Migratorio')], default='civil', max_length=50),
        ),
    ]
