# Generated by Django 6.0.2 on 2026-03-01 01:41

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Tamaño recomendado: 400x400px', null=True, upload_to='perfiles/fotos/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='perfiles/portadas/')),
                ('especialidad', models.CharField(default='Abogado Jurídico', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía Profesional')),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='perfiles/hcv/')),
                ('otp_secret', models.CharField(default=pyotp.random_base32, editable=False, max_length=32)),
                ('mfa_configurado', models.BooleanField(default=False, help_text='Indica si el usuario ya vinculó su Google Authenticator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Abogado',
                'verbose_name_plural': 'Perfiles de Abogados',
            },
        ),
        migrations.CreateModel(
            name='NotaKeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva Nota', max_length=100)),
                ('contenido', models.TextField()),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_keep', to='abogados.perfil')),
            ],
            options={
                'verbose_name': 'Nota Rápida',
                'verbose_name_plural': 'Notas Rápidas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='perfiles/documentos/')),
                ('nombre', models.CharField(default='Archivo sin nombre', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='abogados.perfil')),
            ],
        ),
    ]
