# Generated by Django 6.0.2 on 2026-02-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='perfiles/documentos/')),
                ('nombre', models.CharField(default='Archivo sin nombre', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaKeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva Nota', max_length=100)),
                ('contenido', models.TextField()),
                ('color', models.CharField(default='#ffffff', help_text='Código HEX del color de fondo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota Rápida',
                'verbose_name_plural': 'Notas Rápidas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Tamaño recomendado: 400x400px', null=True, upload_to='perfiles/fotos/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='perfiles/portadas/')),
                ('especialidad', models.CharField(default='Abogado Jurídico', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía Profesional')),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='perfiles/hcv/')),
            ],
            options={
                'verbose_name': 'Perfil de Abogado',
                'verbose_name_plural': 'Perfiles de Abogados',
            },
        ),
    ]
