# Generated by Django 6.0.2 on 2026-03-25 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(default='Abogado Jurídico', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('mfa_activado', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='perfiles/portadas/')),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='perfiles/cv/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abogado',
                'verbose_name_plural': 'Abogados',
                'db_table': 'abogados_perfil',
            },
        ),
        migrations.CreateModel(
            name='NotaKeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva Nota', max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_keep', to='abogados.perfil')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas Keep',
                'db_table': 'abogados_notakeep',
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='perfiles/documentos/')),
                ('nombre', models.CharField(default='Archivo sin nombre', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='abogados.perfil')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Bóveda de Documentos',
            },
        ),
    ]
