# Generated by Django 6.0.2 on 2026-04-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil de Abogado', 'verbose_name_plural': 'Perfiles de Abogados'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mfa_activado',
        ),
    ]
