# Generated by Django 6.0.2 on 2026-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0002_alter_perfil_options_remove_perfil_mfa_activado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
