# Generated by Django 6.0.2 on 2026-02-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notakeep',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
