# Generated by Django 6.0.2 on 2026-02-23 03:27

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0003_alter_notakeep_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mfa_configurado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya vinculó su Google Authenticator'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, editable=False, max_length=32),
        ),
    ]
