# Generated by Django 6.0.2 on 2026-03-01 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_caso', models.CharField(max_length=255)),
                ('contenido_escrito', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='legal_files/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
