# Generated by Django 6.0.2 on 2026-02-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_caso', models.CharField(max_length=255)),
                ('contenido_escrito', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='legal_files/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
