# Generated by Django 6.0.2 on 2026-03-01 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('color_categoria', models.CharField(choices=[('bg-danger', 'Urgente / Pendiente'), ('bg-success', 'Completada / Exitosa'), ('bg-primary', 'General / Cita'), ('bg-info', 'Informativa')], default='bg-primary', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='expedientes.expediente')),
                ('usuarios_asignados', models.ManyToManyField(related_name='audiencias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
