# Generated by Django 6.0.2 on 2026-02-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiencias', '0001_initial'),
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='expedientes.expediente'),
        ),
    ]
