# Generated by Django 6.0.2 on 2026-02-16 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiencias', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='usuarios_asignados',
            field=models.ManyToManyField(related_name='audiencias_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
